# Generated by Django 3.1.7 on 2021-03-17 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='optional_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionName', models.CharField(max_length=30)),
                ('optionImg', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '01000000000' ", regex='^(010|011|012|015)[0-9]+8$')])),
                ('isActive', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('profilePic', models.ImageField(upload_to='images/')),
                ('creationTime', models.DateTimeField()),
                ('token_used_to_active', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_optional_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionValue', models.CharField(max_length=30)),
                ('option_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsers.optional_info')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsers.users')),
            ],
        ),
    ]
