# Generated by Django 3.1.7 on 2021-03-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0005_auto_20210319_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
