# Generated by Django 3.1.7 on 2021-03-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0007_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
