# Generated by Django 3.1.7 on 2021-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0008_remove_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='creationTime',
            field=models.DateTimeField(null=True),
        ),
    ]
