# Generated by Django 3.1.7 on 2021-03-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0011_auto_20210322_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user',
            new_name='userAdmin',
        ),
    ]
