# Generated by Django 3.1.7 on 2021-03-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0012_auto_20210322_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token_used_to_active',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
