# Generated by Django 3.1.7 on 2021-03-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0013_auto_20210323_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
