# Generated by Django 3.1.7 on 2021-03-22 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUsers', '0015_auto_20210323_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userAdmin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
