# Generated by Django 3.1.7 on 2021-03-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='isReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='isReject',
            field=models.BooleanField(default=False),
        ),
    ]
