# Generated by Django 3.1.7 on 2021-03-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProject', '0002_auto_20210330_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='replay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProject.comments'),
        ),
    ]
