# Generated by Django 3.1.7 on 2021-03-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
